apiVersion: v1
kind: Service
metadata:
  name: robot-framework-service
  namespace: default
spec:
  selector:
    io.kompose.service: robot-framework
  type: NodePort
  ports:
        - protocol: TCP
          port: 1471
          targetPort: 1471
          nodePort: 32200
