apiVersion: v1
kind: Service
metadata:
  name: robot-framework-service
  namespace: default
spec:
  selector:
    io.kompose.service: robot-framework
  type: ClusterIP
  ports:
        - protocol: TCP
          port: 99
          targetPort: 99
